# Generated by Django 3.2.7 on 2022-02-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='projectModelImg/')),
                ('previewLink', models.CharField(max_length=500)),
                ('sourceLink', models.CharField(max_length=500)),
                ('ReleasDate', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='skilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=500)),
                ('creator', models.CharField(max_length=25)),
                ('progress_rate', models.CharField(max_length=25)),
                ('ReleasDate', models.CharField(max_length=25)),
            ],
        ),
    ]
